// <auto-generated />
using System;
using Dexture.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Dexture.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20190622175418_Dexture.Models.Context6")]
    partial class DextureModelsContext6
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Dexture.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ContactNo");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Nic");

                    b.Property<string>("Password");

                    b.Property<string>("PersonalAddress");

                    b.HasKey("AdminId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Dexture.Models.AgricultureOfficer", b =>
                {
                    b.Property<int>("AgricultureOfficerId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ContactNo");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Nic");

                    b.Property<string>("Password");

                    b.Property<string>("PersonalAddress");

                    b.HasKey("AgricultureOfficerId");

                    b.ToTable("AgricultureOfficers");
                });

            modelBuilder.Entity("Dexture.Models.Buyer", b =>
                {
                    b.Property<int>("BuyerId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ContactNo");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Nic");

                    b.Property<string>("Password");

                    b.Property<string>("PersonalAddress");

                    b.HasKey("BuyerId");

                    b.ToTable("Buyers");
                });

            modelBuilder.Entity("Dexture.Models.Farmer", b =>
                {
                    b.Property<int>("FarmerId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ContactNo");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("GramaNiladariDivision");

                    b.Property<bool>("IsAccepted");

                    b.Property<string>("LastName");

                    b.Property<string>("Nic");

                    b.Property<string>("Password");

                    b.Property<string>("PersonalAddress");

                    b.HasKey("FarmerId");

                    b.ToTable("Farmers");
                });

            modelBuilder.Entity("Dexture.Models.Land", b =>
                {
                    b.Property<int>("LandId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("FarmerId");

                    b.Property<string>("Location");

                    b.Property<double>("Size");

                    b.HasKey("LandId");

                    b.HasIndex("FarmerId");

                    b.ToTable("Lands");
                });

            modelBuilder.Entity("Dexture.Models.Land", b =>
                {
                    b.HasOne("Dexture.Models.Farmer", "FarmerID")
                        .WithMany("Lands")
                        .HasForeignKey("FarmerId");
                });
#pragma warning restore 612, 618
        }
    }
}
